// Fill out your copyright notice in the Description page of Project Settings.


#include "BGGasCharacterDefaults.h"

#if WITH_EDITOR
void UBGGasCharacterDefaults::PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent)
{
	Super::PostEditChangeProperty(PropertyChangedEvent);

	const FProperty* Property = PropertyChangedEvent.Property;
	if (Property && Property->GetFName() == GET_MEMBER_NAME_CHECKED(UBGGasCharacterDefaults, InputAbilities) && !InputAbilities.IsEmpty())
	{
		TArray<FBGGameplayInputAbilityInfo> InputAbilitiesArray = InputAbilities.Array();
		InputAbilities.Reset();
  
		for (int32 i = 0; i < InputAbilitiesArray.Num(); ++i)
		{
			FBGGameplayInputAbilityInfo& Info = InputAbilitiesArray[i];
			Info.AutoGeneratedInputID = i;
			InputAbilities.Add(Info);
		}
	}
}
#endif